title: Brandon Lehr
email: blehr.mail@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Home of Brandon Lehr, Web Developer, Blogger, Builder of Things
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brandonlehr.com" # the base hostname & protocol for your site
logo: "/images/profilefunky.jpg"
timezone:
locale: en
author:
  twitter: brandonlehr
twitter:
  username: brandonlehr

permalink: pretty 
  
social:
  name: Brandon Lehr
  links: [
    "http://www.linkedin.com/in/brandonlehr",
    "http://plus.google.com/+BrandonLehr",
    "https://twitter.com/brandonlehr",
    "https://github.com/blehr"  
  ]
  
disqus_shortname: brandonlehr.disqus.com

# Build settings
markdown: kramdown
#Gems
gems: [
  jekyll-paginate, 
  jekyll-sitemap, 
  jekyll-seo-tag, 
  jekyll-mentions, 
  jemoji, 
  jekyll-redirect-from, 
  jekyll-sitemap, 
  jekyll-feed
]

paginate: 10
paginate_path: "/blog/page:num/"
exclude: [
  package.json,
  node_modules,
  gulpfile.js,
  _app,
]
